# SPDX-License-Identifier: MIT
"""Tax form PDFs — the arithmetic of v0.34.0 drawn on the face of the form.

v0.36.0. `form_generators.py` computes what goes in each box. This draws the
boxes, in the official numbering and roughly the official arrangement, and puts
the computed value in each one. Same contract as the generators: PURE
FUNCTIONS. No database reads, no attachment writing, no side effects — a form
dict and two blocks of identifying text go in, PDF bytes come out, and the
whole thing can be checked against a fixture.

WHAT THESE ARE, SAID PLAINLY AND SAID ON EVERY PAGE. A working copy. An
official Copy A of a W-2 or a 1099 is printed in a specific red ink that the
IRS's scanners drop out, and no laser printer produces it; Oregon's and
Washington's returns are filed through Frances Online and ESD's portal, not on
paper this app made. So every page carries the header note and a disclaimer
block naming the agency and its real filing channel. These pages are for the
farmer's records, for a review before filing, and for keying the numbers into
the portal that does the filing — nothing else. Rendering one is not a filing
and changes no form's status.

THE FORM DATA IS THE RECORD; THE ARGUMENTS ONLY FILL HOLES. `form_data` was
computed and stored once, at generation, and it already carries the employer
and recipient blocks as they were then. `company_info` and the subject block
are consulted ONLY where `form_data` has nothing — an address that was never on
the Company when the form was generated, for instance. A renderer that
preferred today's arguments would print a form that disagrees with the record
it claims to render, which is the exact failure `taxforms.py` stores
`form_data_json` to avoid.

REPORTLAB IS OPTIONAL AT IMPORT TIME, like shapely, h3 and segno before it. A
bench without it loses exactly two tools — `render_tax_form_pdf` and
`bulk_render_tax_form_pdfs` — which say so by name with the pip command to fix
it, rather than failing to load the other three hundred and twenty-six. Every
generator and every other tax-form tool works without it: the numbers are the
deliverable and the page is a convenience.

TWO DELIBERATE CHOICES IN THE OUTPUT.

  * **No stream compression.** These pages are a few kilobytes and an
    uncompressed content stream is one a person can `grep` and `diff` — the
    same judgement `render/pdf.py` made, and it is what lets a test assert that
    a box value actually reached the page rather than that a renderer ran.
  * **Text is folded to ASCII.** The generators write prose with em dashes and
    curly quotes; the base-14 fonts here are WinAnsi and a stray character
    outside it is an exception at draw time rather than a mark on the page. So
    `_clean` folds the handful that occur and drops anything else, and a
    hyphen where an em dash was is a cost worth paying for a page that cannot
    fail to draw.
"""

from __future__ import annotations

import io

from .errors import ToolError

try:  # pragma: no cover - exercised by whichever branch the test bench has
	from reportlab.pdfgen import canvas as rl_canvas

	HAVE_REPORTLAB = True
except Exception:  # pragma: no cover - a bench without the dependency
	rl_canvas = None
	HAVE_REPORTLAB = False


#: US Letter, portrait, in points. Not configurable — these pages are printed
#: and filed in the United States, and a page size that varied between runs
#: would make two copies of one form physically different objects.
PAGE_WIDTH = 612.0
PAGE_HEIGHT = 792.0

#: Half an inch on every side. Tighter than `render/pdf.py`'s three quarters
#: because a tax form is a grid that has to fit, not prose that can reflow.
MARGIN = 36.0
CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN

#: Where the page furniture sits, measured from the top and bottom edges.
HEADER_BASELINE = 24.0
BODY_TOP = 44.0
FOOTER_TOP = PAGE_HEIGHT - 46.0
FOOTER_LIMIT = PAGE_HEIGHT - 52.0

FONT_LABEL = "Helvetica"
FONT_LABEL_BOLD = "Helvetica-Bold"
FONT_VALUE = "Courier-Bold"
FONT_PLAIN = "Courier"
FONT_NOTE = "Helvetica-Oblique"

SIZE_TITLE = 15.0
SIZE_SUBTITLE = 8.5
SIZE_HEADING = 9.5
SIZE_LABEL = 6.0
SIZE_VALUE = 9.0
SIZE_SMALL = 7.0

#: The line at the head of every page. Required on every form this module
#: produces, and the shortest true statement about what the page is.
HEADER_NOTE = "Generated by Farm Task Dispatch - verify before filing"

#: The block at the foot of every page. `{channel}` is where the form actually
#: gets filed, which differs per agency and is the part a reader needs.
DISCLAIMER = (
	"WORKING COPY - NOT AN OFFICIAL FORM. This page was produced from payroll "
	"records held in this system and has not been reviewed by anyone. It is not "
	"a filing and cannot be submitted in place of one. {channel} Check every "
	"figure, and read the notes below before this page is used for anything."
)

#: How each form is really filed. Naming the channel is the difference between
#: a disclaimer somebody reads and one they scroll past.
FILING_CHANNEL = {
	"W-2": (
		"Copy A must be the official scannable red-ink form or an SSA electronic "
		"filing through Business Services Online; Copy B and Copy C print on plain "
		"paper and are the copies that go to the employee."
	),
	"1099-NEC": (
		"Copy A must be the official scannable red-ink form or an IRS electronic "
		"filing through IRIS or FIRE; Copy B prints on plain paper and is the copy "
		"that goes to the recipient."
	),
	"941": (
		"Form 941 is filed on the official IRS form or electronically through an "
		"authorised e-file provider, and deposits are made through EFTPS."
	),
	"OR-WR": ("Form OR-WR is filed with the Oregon Department of Revenue through Revenue Online."),
	"OQ": (
		"Form OQ is filed with the Oregon Employment Department and the Department "
		"of Revenue through Frances Online."
	),
	"WA-ESD": (
		"The quarterly report is filed with the Washington Employment Security Department through EAMS."
	),
	"940": (
		"Form 940 is filed on the official IRS form or electronically through an authorised e-file provider; "
		"FUTA deposits are made through EFTPS."
	),
	"W-3": (
		"The W-3 goes to the SSA with Copy A of the W-2s — on the official scannable red-ink form, or filed "
		"electronically through Business Services Online, which builds the W-3 itself."
	),
}

#: Which copy of a recipient form this module draws, and who it is for. Only
#: the plain-paper copies: Copy A is red ink nobody's printer makes.
W2_COPY = "Copy B - To Be Filed With Employee's FEDERAL Tax Return"
NEC_COPY = "Copy B - For Recipient"

#: Characters the generators write that the base-14 fonts cannot draw, and
#: what each becomes. Anything else outside ASCII is dropped by `_clean`.
_FOLD = {
	"—": "-",
	"–": "-",
	"‘": "'",
	"’": "'",
	"“": '"',
	"”": '"',
	"…": "...",
	" ": " ",
	"×": "x",
	"−": "-",
	"§": "Sec.",
	"≥": ">=",
	"≤": "<=",
}

PRODUCER = "erpnext_mcp"


# ── availability ────────────────────────────────────────────────────────────


def available() -> bool:
	"""Can this bench draw a form at all? Never raises."""
	return HAVE_REPORTLAB


def requires_sentence() -> str:
	return (
		"the reportlab Python package, which this app declares as a dependency — install it "
		"into the bench's environment with `./env/bin/pip install 'reportlab>=4.0'` and restart"
	)


def require() -> None:
	if not available():
		raise ToolError(
			f"this site is missing {requires_sentence()}. The form's computed values are "
			f"unaffected — read them with get_tax_form. Nothing was changed."
		)


# ── text and money ──────────────────────────────────────────────────────────


def _clean(text) -> str:
	"""Fold prose to something the base-14 fonts can draw. Never raises."""
	if text is None:
		return ""
	out = str(text)
	for character, replacement in _FOLD.items():
		out = out.replace(character, replacement)
	return "".join(character if 32 <= ord(character) < 127 else " " for character in out)


def _money(value, blank_zero: bool = False) -> str:
	"""A figure as it belongs in a box: grouped, two places, never a bare int."""
	try:
		amount = float(value or 0)
	except (TypeError, ValueError):
		return ""
	if blank_zero and abs(amount) < 0.005:
		return ""
	return f"{amount:,.2f}"


def _whole(value) -> str:
	try:
		return f"{round(float(value or 0)):,}"
	except (TypeError, ValueError):
		return ""


def _first(*values) -> str:
	"""The first of several sources that actually says something."""
	for value in values:
		text = str(value or "").strip()
		if text:
			return text
	return ""


def _bare_ssn(display) -> str:
	"""`XXX-XX-1234`, without the generator's parenthetical.

	`_ssn_display` returns `XXX-XX-____  (no SSN on file)`, which is exactly
	right in a tool result and two and a half times too wide for a column in a
	wage-detail table. The parenthetical is not lost: the generator raises a
	warning naming every employee whose number is missing, and it prints in full
	in the notes.
	"""
	return str(display or "").split("  (")[0].strip()


def _address_lines(address: str, limit: int = 3) -> list[str]:
	"""One stored address string as the two or three lines a box has room for.

	Split on commas, because that is how every address on this site is stored —
	`_employee_info` in `tools/taxforms.py` joins the I-9's street, city and
	state/ZIP with them. A caller who stored newlines gets those honoured too.
	"""
	raw = str(address or "").replace("\n", ",")
	parts = [part.strip() for part in raw.split(",") if part.strip()]
	if not parts:
		return []
	if len(parts) <= limit:
		return parts
	# Fold the overflow into the last line rather than dropping it: a ZIP code
	# that vanished because an address had one comma too many is the kind of
	# quiet wrongness a printed form should never have.
	return [*parts[: limit - 1], ", ".join(parts[limit - 1 :])]


# ── the sheet ───────────────────────────────────────────────────────────────


class _Sheet:
	"""One form: a grid of labelled boxes, then a flowing notes section.

	Geometry is TOP-DOWN. Every `top` argument is points from the top edge of
	the page, because that is how a form is described — "box 1 is an inch from
	the top" — and converting once here beats inverting a coordinate in forty
	call sites. `self.top` is the cursor the flowing half advances.

	v0.91.0. THE PAGE FURNITURE IS NOW AN ARGUMENT, AND THE DEFAULTS ARE THE SIX
	TAX FORMS' EXACTLY. `pay_stub_pdf.py` draws on this class because the boxes,
	the clipping, the wrap and the pagination are the same problem — but a pay
	stub is NOT a working copy of anything. It is the statement of earnings an
	employer is required to hand a worker (ORS 652.610, RCW 49.46.020), it is
	produced from the slip that was actually paid, and stamping "NOT AN OFFICIAL
	FORM - this is not a filing" across it would be a false statement about the
	one document on this site that IS the record it looks like.

	So `header_note`, `page_label` and `footer` may be given, and every one of
	them defaults to what the tax forms have always drawn. A caller that passes
	none gets a byte-identical page to the one v0.36.0 produced, which is what
	`Disclaimers` in `test_tax_form_pdfs.py` goes on asserting.
	"""

	def __init__(
		self,
		form_type: str,
		title: str,
		subject: str,
		header_note: str = "",
		page_label: str = "",
		footer: str = "",
	):
		self._buffer = io.BytesIO()
		self._canvas = rl_canvas.Canvas(
			self._buffer,
			pagesize=(PAGE_WIDTH, PAGE_HEIGHT),
			# See the module docstring: a few kilobytes, and a stream a person
			# can read is a stream a test can assert against.
			pageCompression=0,
		)
		self._canvas.setTitle(_clean(title))
		self._canvas.setSubject(_clean(subject))
		self._canvas.setAuthor(PRODUCER)
		self._canvas.setCreator(PRODUCER)
		self._form_type = form_type
		self._channel = FILING_CHANNEL.get(form_type, "")
		self._header_note = header_note or HEADER_NOTE
		self._page_label = page_label or f"{form_type} - working copy"
		self._footer = footer or DISCLAIMER.format(channel=self._channel)
		self._page_number = 0
		self.top = BODY_TOP
		self._begin_page()

	# -- primitives ----------------------------------------------------------
	def _y(self, top: float) -> float:
		return PAGE_HEIGHT - top

	def width_of(self, text: str, font: str, size: float) -> float:
		return self._canvas.stringWidth(_clean(text), font, size)

	def clip(self, text: str, width: float, font: str, size: float) -> str:
		"""Shorten `text` until it fits, marking that it was shortened.

		Every value drawn inside a box goes through this. A figure that runs
		past its own rule and over the next box's is worse than a truncated one:
		it looks like it belongs to the column it has spilled into.
		"""
		body = _clean(text)
		if self.width_of(body, font, size) <= width:
			return body
		while body and self.width_of(body + ".", font, size) > width:
			body = body[:-1]
		return body + "."

	def text(
		self,
		x: float,
		baseline_top: float,
		text: str,
		font: str = FONT_LABEL,
		size: float = SIZE_LABEL,
		align: str = "left",
	) -> None:
		"""One string, its BASELINE at `baseline_top` points from the page top."""
		body = _clean(text)
		if not body:
			return
		self._canvas.setFont(font, size)
		if align == "right":
			self._canvas.drawRightString(x, self._y(baseline_top), body)
		elif align == "center":
			self._canvas.drawCentredString(x, self._y(baseline_top), body)
		else:
			self._canvas.drawString(x, self._y(baseline_top), body)

	def rect(self, x: float, top: float, width: float, height: float, line_width: float = 0.6) -> None:
		self._canvas.setLineWidth(line_width)
		self._canvas.rect(x, self._y(top + height), width, height, stroke=1, fill=0)

	def line(self, x1: float, top: float, x2: float, line_width: float = 0.5) -> None:
		self._canvas.setLineWidth(line_width)
		self._canvas.line(x1, self._y(top), x2, self._y(top))

	def fill_rect(self, x: float, top: float, width: float, height: float, grey: float = 0.9) -> None:
		self._canvas.setFillGray(grey)
		self._canvas.rect(x, self._y(top + height), width, height, stroke=0, fill=1)
		self._canvas.setFillGray(0)

	# -- boxes ---------------------------------------------------------------
	def box(
		self,
		x: float,
		top: float,
		width: float,
		height: float,
		label: str = "",
		value="",
		value_font: str = FONT_VALUE,
		value_size: float = SIZE_VALUE,
		value_align: str = "left",
		label_font: str = FONT_LABEL,
	) -> None:
		"""One numbered box: a rule around it, its label small at the top-left,
		its value beneath. `value` may be a string or a list of lines.

		The label WRAPS and the value CLIPS, and the asymmetry is deliberate: a
		label is prose that can take a second line, and a figure that took a
		second line would read as two figures.
		"""
		self.rect(x, top, width, height)
		lines = value if isinstance(value, (list, tuple)) else [value]
		lines = [_clean(line) for line in lines if str(line or "").strip()]

		if label:
			room = height - ((value_size + 6.0) if lines else 4.0)
			allowed = max(1, min(3, int(room / (SIZE_LABEL + 1.5))))
			for index, part in enumerate(self.wrap(label, width - 6, label_font, SIZE_LABEL)[:allowed]):
				self.text(
					x + 3,
					top + SIZE_LABEL + 2.5 + index * (SIZE_LABEL + 1.5),
					part,
					label_font,
					SIZE_LABEL,
				)

		if not lines:
			return
		leading = value_size + 2.0
		first = top + height - 4.5 - leading * (len(lines) - 1)
		for index, line in enumerate(lines):
			baseline = first + leading * index
			body = self.clip(line, width - 8, value_font, value_size)
			if value_align == "right":
				self.text(x + width - 4, baseline, body, value_font, value_size, align="right")
			elif value_align == "center":
				self.text(x + width / 2, baseline, body, value_font, value_size, align="center")
			else:
				self.text(x + 4, baseline, body, value_font, value_size)

	def money_box(self, x: float, top: float, width: float, height: float, label: str, value) -> None:
		"""A box whose value is a figure, and figures are right-aligned."""
		self.box(x, top, width, height, label, _money(value), value_align="right")

	def checkbox(self, x: float, top: float, label: str, ticked: bool, size: float = 7.5) -> float:
		"""A tick box with its label to the right. Returns the width consumed."""
		self.rect(x, top, size, size, line_width=0.6)
		if ticked:
			self._canvas.setLineWidth(1.1)
			self._canvas.line(x + 1.4, self._y(top + size - 1.4), x + size - 1.4, self._y(top + 1.4))
			self._canvas.line(x + 1.4, self._y(top + 1.4), x + size - 1.4, self._y(top + size - 1.4))
		self.text(x + size + 3, top + size - 0.8, label, FONT_LABEL, SIZE_SMALL)
		return size + 6 + self.width_of(label, FONT_LABEL, SIZE_SMALL)

	def ink(
		self, x: float, baseline_top: float, image_bytes: bytes, max_width: float, max_height: float
	) -> bool:
		"""Draw a signature capture sitting ON a ruled line. True if it landed.

		THE CROPPING IS `pdf_signing.ink_only`, NOT A SECOND ONE. That function
		already knows what a capture from this app's pad looks like — a mostly
		white PNG with a stroke somewhere in it — and trims to the stroke so a
		signature drawn in the corner of a canvas does not render as a dot in the
		middle of a box. A second implementation here would be a second answer to
		"where is the ink", and the two would disagree on the same picture.

		ANCHORED TO THE BASELINE AND GROWING UPWARD, because that is where
		handwriting goes on a printed rule. Scaled to fit both bounds, never
		stretched: a signature squashed to fill a box is not the mark that was
		made.

		FALSE RATHER THAN AN EXCEPTION on a bench without Pillow or reportlab's
		image reader, or on bytes that hold no ink. The caller draws the ruled
		line either way and the page says the row is unsigned, which is a true
		statement about a sheet somebody has to go and finish.
		"""
		from . import pdf_signing

		prepared = pdf_signing.ink_only(image_bytes)
		if not prepared:
			return False
		try:
			from reportlab.lib.utils import ImageReader
		except ImportError:  # pragma: no cover - a bench without reportlab cannot be here
			return False
		png, ink_width, ink_height = prepared
		if ink_width <= 0 or ink_height <= 0:
			return False
		scale = min(max_width / ink_width, max_height / ink_height)
		width, height = ink_width * scale, ink_height * scale
		try:
			self._canvas.drawImage(
				ImageReader(io.BytesIO(png)),
				x,
				self._y(baseline_top),
				width=width,
				height=height,
				mask="auto",
			)
		except Exception:  # pragma: no cover - an image reportlab will not decode
			return False
		return True

	# -- the flowing half ----------------------------------------------------
	def masthead(self, title: str, form_line: str, right: str, copy_line: str = "") -> None:
		"""The band every form opens with: what it is, for when, and which copy."""
		self.text(MARGIN, self.top + SIZE_TITLE, title, FONT_LABEL_BOLD, SIZE_TITLE)
		self.text(
			PAGE_WIDTH - MARGIN,
			self.top + SIZE_TITLE,
			right,
			FONT_LABEL_BOLD,
			SIZE_TITLE,
			align="right",
		)
		self.top += SIZE_TITLE + 3
		self.text(MARGIN, self.top + SIZE_SUBTITLE, form_line, FONT_LABEL, SIZE_SUBTITLE)
		self.top += SIZE_SUBTITLE + 2
		if copy_line:
			self.text(MARGIN, self.top + SIZE_SUBTITLE, copy_line, FONT_LABEL_BOLD, SIZE_SUBTITLE)
			self.top += SIZE_SUBTITLE + 2
		self.line(MARGIN, self.top + 2, PAGE_WIDTH - MARGIN, line_width=1.1)
		self.top += 8

	def heading(self, text: str) -> None:
		self.room_for(SIZE_HEADING + 14)
		self.top += 6
		self.text(MARGIN, self.top + SIZE_HEADING, text, FONT_LABEL_BOLD, SIZE_HEADING)
		self.top += SIZE_HEADING + 2
		self.line(MARGIN, self.top, PAGE_WIDTH - MARGIN, line_width=0.75)
		self.top += 5

	def paragraph(
		self, text: str, size: float = SIZE_SMALL, font: str = FONT_LABEL, indent: float = 0.0
	) -> None:
		for line in self.wrap(text, CONTENT_WIDTH - indent, font, size):
			self.room_for(size + 2.5)
			self.text(MARGIN + indent, self.top + size, line, font, size)
			self.top += size + 2.5

	def bullets(self, items, size: float = SIZE_SMALL) -> None:
		for item in items:
			lines = self.wrap(str(item), CONTENT_WIDTH - 12, FONT_LABEL, size)
			for index, line in enumerate(lines):
				self.room_for(size + 2.5)
				prefix = "- " if index == 0 else "  "
				self.text(MARGIN + 2, self.top + size, prefix + line, FONT_LABEL, size)
				self.top += size + 2.5
			self.top += 1.5

	def spacer(self, points: float = 5.0) -> None:
		self.top += points

	def wrap(self, text: str, width: float, font: str, size: float) -> list[str]:
		"""Greedy wrap measured in points, not guessed in characters.

		A line that already fits comes back UNTOUCHED, spacing and all. Wrapping
		splits on whitespace and rejoins with single spaces, which would quietly
		turn `1  Wages, tips, other compensation` — the real form's two spaces
		after a box number — into something that only looks like it.
		"""
		body = _clean(text)
		if not body:
			return []
		if "\n" not in body and self.width_of(body, font, size) <= width:
			return [body]
		lines: list[str] = []
		for paragraph in body.split("\n"):
			current = ""
			for word in paragraph.split():
				candidate = f"{current} {word}".strip()
				if current and self.width_of(candidate, font, size) > width:
					lines.append(current)
					current = word
				else:
					current = candidate
			lines.append(current)
		return [line for line in lines if line != ""] or [""]

	# -- pagination ----------------------------------------------------------
	def room_for(self, height: float) -> None:
		if self.top + height > FOOTER_LIMIT:
			self.page_break()

	def page_break(self) -> None:
		self._finish_page()
		self._canvas.showPage()
		self.top = BODY_TOP
		self._begin_page()

	def _begin_page(self) -> None:
		self._page_number += 1
		self.text(MARGIN, HEADER_BASELINE, self._header_note, FONT_LABEL_BOLD, SIZE_SMALL)
		self.text(
			PAGE_WIDTH - MARGIN,
			HEADER_BASELINE,
			f"{self._page_label} - page {self._page_number}",
			FONT_LABEL,
			SIZE_SMALL,
			align="right",
		)
		self.line(MARGIN, HEADER_BASELINE + 4, PAGE_WIDTH - MARGIN, line_width=0.75)

	def _finish_page(self) -> None:
		"""The footer band. Drawn last on every page, so a page cannot exist
		without it — including one that only exists because a table overflowed."""
		self.line(MARGIN, FOOTER_TOP - 6, PAGE_WIDTH - MARGIN, line_width=0.75)
		body = self._footer
		top = FOOTER_TOP
		for line in self.wrap(body, CONTENT_WIDTH, FONT_NOTE, 6.2)[:4]:
			self.text(MARGIN, top, line, FONT_NOTE, 6.2)
			top += 7.6

	def render(self) -> bytes:
		"""The whole document as PDF bytes. Callable once per sheet."""
		self._finish_page()
		self._canvas.showPage()
		self._canvas.save()
		return self._buffer.getvalue()


# ── shared blocks ───────────────────────────────────────────────────────────


def _employer(form_data: dict, company_info: dict, key: str = "employer") -> dict:
	"""The employer block as it goes on the page: record first, argument second."""
	block = dict(form_data.get(key) or {})
	info = dict(company_info or {})
	ein = _first(block.get("ein"), info.get("ein"))
	return {
		"name": _first(block.get("name"), info.get("name")),
		"ein": ein or "__-_______  (set the company's Tax ID)",
		"address": _address_lines(_first(block.get("address"), info.get("address"))),
	}


def _period_line(form_data: dict) -> str:
	start = _first(form_data.get("period_start"))
	end = _first(form_data.get("period_end"))
	if start and end:
		return f"Period covered: {start} to {end}"
	return ""


def _notes(sheet: _Sheet, form_data: dict, extra: list[str] | None = None) -> None:
	"""The section a reader is told to read first, at the foot of every form.

	The generator's `warnings` are reproduced verbatim and in full. They are the
	only place a form says which of its figures is a floor rather than a figure,
	and a page that dropped them would look more certain than the arithmetic
	behind it.
	"""
	sheet.heading("Before this form is filed")
	for note in extra or []:
		sheet.paragraph(note)
		sheet.spacer(2)

	warnings = [w for w in (form_data.get("warnings") or []) if str(w or "").strip()]
	if warnings:
		sheet.paragraph(
			f"The generator raised {len(warnings)} note(s) on this form. Each one names a "
			"figure it had to assume rather than know:",
			font=FONT_LABEL_BOLD,
		)
		sheet.spacer(2)
		sheet.bullets(warnings)
	else:
		sheet.paragraph(
			"The generator raised no notes on this form: every figure was computed from "
			"payroll records held in this system, with nothing assumed."
		)


def _sheet_for(form_type: str, form_data: dict, what: str) -> _Sheet:
	require()
	year = form_data.get("tax_year") or ""
	quarter = form_data.get("quarter") or ""
	label = f"{form_type} {year}{' ' + str(quarter) if quarter else ''}".strip()
	return _Sheet(form_type, f"Form {label} - working copy", what)


# ── W-2 ─────────────────────────────────────────────────────────────────────


def render_w2_pdf(form_data: dict, company_info: dict, employee_info: dict) -> bytes:
	"""Render a W-2 Wage and Tax Statement PDF.

	Produces Copy B (for employee) layout with all boxes filled.

	Args:
		form_data: What `form_generators.generate_w2_data` returned.
		company_info: The employer block, consulted only where `form_data` is
			silent — `name`, `ein`, `address`.
		employee_info: The recipient block, same rule — `employee_name`,
			`ssn_display` or `ssn_last4`, `address`.

	Returns:
		PDF bytes. One page of form face, plus however many the notes take.
	"""
	form_data = dict(form_data or {})
	year = form_data.get("tax_year") or ""
	sheet = _sheet_for("W-2", form_data, f"Wage and Tax Statement {year}")

	employer = _employer(form_data, company_info)
	block = dict(form_data.get("employee") or {})
	info = dict(employee_info or {})
	name = _first(block.get("name"), info.get("employee_name"), info.get("name"), block.get("employee"))
	ssn = _first(block.get("ssn_display"), info.get("ssn_display"))
	if not ssn:
		last4 = str(info.get("ssn_last4") or "").strip()[-4:]
		ssn = f"XXX-XX-{last4}" if last4 else "XXX-XX-____  (no SSN on file)"
	address = _address_lines(_first(block.get("address"), info.get("address")), limit=2)

	sheet.masthead(
		"Form W-2",
		"Wage and Tax Statement",
		str(year),
		W2_COPY,
	)

	# The face is a TEN-ROW GRID of 26 points, and both halves are cut to it.
	# The left column is the identifying half (boxes a to f) and the right is the
	# money, two boxes wide, in the real form's numbering. The two columns end on
	# the same rule because a form whose halves stop at different heights reads
	# as a form with something missing from the shorter one.
	top = sheet.top
	row_h = 26.0
	rows = 10
	face_height = row_h * rows
	left_w = 250.0
	col_w = (CONTENT_WIDTH - left_w) / 2
	col1 = MARGIN + left_w
	col2 = col1 + col_w

	left_boxes = (
		(30.0, "a  Employee's social security number", [ssn], FONT_VALUE, SIZE_VALUE),
		(30.0, "b  Employer identification number (EIN)", [employer["ein"]], FONT_VALUE, SIZE_VALUE),
		(
			64.0,
			"c  Employer's name, address, and ZIP code",
			[employer["name"], *employer["address"]][:3] or ["(not recorded on this site)"],
			FONT_PLAIN,
			8.0,
		),
		(28.0, "d  Control number", [str(form_data.get("control_number") or "")], FONT_VALUE, SIZE_VALUE),
		(36.0, "e  Employee's first name and initial, last name, and suffix", [name], FONT_VALUE, SIZE_VALUE),
		(
			72.0,
			"f  Employee's address and ZIP code",
			address or ["(not recorded on this site)"],
			FONT_PLAIN,
			8.0,
		),
	)
	offset = 0.0
	for height, label, value, font, size in left_boxes:
		sheet.box(MARGIN, top + offset, left_w, height, label, value, value_font=font, value_size=size)
		offset += height

	money_rows = (
		(
			"1  Wages, tips, other compensation",
			"box1_wages",
			"2  Federal income tax withheld",
			"box2_federal_income_tax_withheld",
		),
		(
			"3  Social security wages",
			"box3_social_security_wages",
			"4  Social security tax withheld",
			"box4_social_security_tax_withheld",
		),
		(
			"5  Medicare wages and tips",
			"box5_medicare_wages",
			"6  Medicare tax withheld",
			"box6_medicare_tax_withheld",
		),
		("7  Social security tips", "box7_social_security_tips", "8  Allocated tips", "box8_allocated_tips"),
		("9", None, "10  Dependent care benefits", "box10_dependent_care_benefits"),
		("11  Nonqualified plans", "box11_nonqualified_plans", None, None),
	)
	for index, (left_label, left_key, right_label, right_key) in enumerate(money_rows):
		row_top = top + index * row_h
		if left_key:
			sheet.money_box(col1, row_top, col_w, row_h, left_label, form_data.get(left_key))
		else:
			sheet.box(col1, row_top, col_w, row_h, left_label, "")
		if right_label:
			if right_key:
				sheet.money_box(col2, row_top, col_w, row_h, right_label, form_data.get(right_key))
			else:
				sheet.box(col2, row_top, col_w, row_h, right_label, "")

	# Box 12 stacks four codes down the right; box 13's three ticks and box 14's
	# other-withholding lines sit beside it.
	codes = list(form_data.get("box12_codes") or [])
	for index in range(4):
		letter = "abcd"[index]
		entry = codes[index] if index < len(codes) else {}
		code = _clean(str((entry or {}).get("code") or ""))
		amount = _money((entry or {}).get("amount"), blank_zero=True) if entry else ""
		# 12d takes the last two rows so the right column closes on the same
		# rule as box 14 beside it.
		height = row_h * (2 if index == 3 else 1)
		sheet.box(
			col2,
			top + (5 + index) * row_h,
			col_w,
			height,
			f"12{letter}",
			f"{code}   {amount}".strip(),
			value_align="right",
		)

	# Box 13's three ticks STACK. Side by side they do not fit the column, and
	# the third one ends up drawn over box 12b — a tick in the wrong box on a
	# wage statement is not a cosmetic problem.
	box13 = dict(form_data.get("box13") or {})
	b13_top = top + 6 * row_h
	sheet.box(col1, b13_top, col_w, row_h * 2, "13", "")
	for index, (label, key) in enumerate(
		(
			("Statutory employee", "statutory_employee"),
			("Retirement plan", "retirement_plan"),
			("Third-party sick pay", "third_party_sick_pay"),
		)
	):
		sheet.checkbox(col1 + 5, b13_top + 12 + index * 13, label, bool(box13.get(key)), size=6.5)

	box14 = list(form_data.get("box14_other") or [])
	fourteen = [f"{item.get('code', '')}  {_money(item.get('amount'))}" for item in box14[:3]]
	if len(box14) > 3:
		fourteen = [*fourteen[:2], f"+ {len(box14) - 2} more, see notes"]
	sheet.box(col1, top + 8 * row_h, col_w, row_h * 2, "14  Other", fourteen, value_size=7.5)

	sheet.top = top + face_height + 6

	# Boxes 15 to 20, one row per state the worker had wages in.
	_w2_state_table(sheet, form_data)

	extra = []
	if box14:
		extra.append(
			"Box 14 carries the state levies that are withheld but are not income tax: "
			+ "; ".join(
				f"{item.get('code', '')} {_money(item.get('amount'))} ({item.get('description', '')})"
				for item in box14
			)
			+ "."
		)
	extra.append(
		"The social security number is printed as four digits because this system stores "
		"four and never nine. Complete the rest from the employee's I-9 or Social Security "
		"card before the copy is furnished."
	)
	_notes(sheet, form_data, extra)
	return sheet.render()


def _w2_state_table(sheet: _Sheet, form_data: dict) -> None:
	"""Boxes 15 through 20 across the full width, one row per state."""
	# Every width is set so its box number and label fit on ONE line. A header
	# that wraps loses the two spaces after the box number, and "20 Locality
	# name" is not what the form calls box 20.
	columns = (
		("15  State", 44.0, "box15_state", "text"),
		("Employer's state ID number", 100.0, "box15_employer_state_id", "text"),
		("16  State wages, tips, etc.", 92.0, "box16_state_wages", "money"),
		("17  State income tax", 78.0, "box17_state_income_tax", "money"),
		("18  Local wages, tips, etc.", 88.0, "box18_local_wages", "money"),
		("19  Local income tax", 76.0, "box19_local_income_tax", "money"),
		("20  Locality name", 62.0, "box20_locality_name", "text"),
	)
	rows = list(form_data.get("state_boxes") or [])
	sheet.room_for(20 + 20 * max(1, len(rows)))

	top = sheet.top
	x = MARGIN
	for label, width, _key, _kind in columns:
		sheet.rect(x, top, width, 20)
		for index, line in enumerate(sheet.wrap(label, width - 5, FONT_LABEL, SIZE_LABEL)[:2]):
			sheet.text(x + 3, top + SIZE_LABEL + 2.5 + index * 7, line, FONT_LABEL, SIZE_LABEL)
		x += width

	if not rows:
		rows = [{}]
	for row_index, row in enumerate(rows):
		row_top = top + 20 + row_index * 20
		x = MARGIN
		for _label, width, key, kind in columns:
			value = _money(row.get(key)) if kind == "money" else _clean(row.get(key) or "")
			sheet.box(
				x,
				row_top,
				width,
				20,
				"",
				value,
				value_size=8.0,
				value_align="right" if kind == "money" else "left",
			)
			x += width
	sheet.top = top + 20 + 20 * len(rows)


# ── 1099-NEC ────────────────────────────────────────────────────────────────


def render_1099_nec_pdf(form_data: dict, company_info: dict, contractor_info: dict) -> bytes:
	"""Render a 1099-NEC PDF.

	Copy B, the plain-paper copy that goes to the recipient. Copy A is red ink
	nobody's printer makes, and the disclaimer says so.

	Args:
		form_data: What `form_generators.generate_1099_nec_data` returned.
		company_info: The payer block, consulted only where `form_data` is silent.
		contractor_info: The recipient block, same rule — `party_name`,
			`tin_last4` or `tin_display`, `address`.

	Returns:
		PDF bytes.
	"""
	form_data = dict(form_data or {})
	year = form_data.get("tax_year") or ""
	sheet = _sheet_for("1099-NEC", form_data, f"Nonemployee compensation {year}")

	payer = _employer(form_data, company_info, key="payer")
	block = dict(form_data.get("recipient") or {})
	info = dict(contractor_info or {})
	name = _first(block.get("name"), info.get("party_name"), info.get("name"), block.get("party"))
	tin = _first(block.get("tin_display"), info.get("tin_display"))
	if not tin:
		last4 = str(info.get("tin_last4") or "").strip()[-4:]
		tin = f"XXX-XX-{last4}" if last4 else "__________  (no taxpayer id - obtain a signed W-9)"
	address = _address_lines(_first(block.get("address"), info.get("address")), limit=3)

	sheet.masthead("Form 1099-NEC", "Nonemployee Compensation", str(year), NEC_COPY)

	top = sheet.top
	left_w = 300.0
	right_x = MARGIN + left_w
	right_w = CONTENT_WIDTH - left_w

	sheet.box(
		MARGIN,
		top,
		left_w,
		66,
		"PAYER'S name, street address, city or town, state, ZIP code, and telephone no.",
		[payer["name"], *payer["address"]][:4] or ["(not recorded on this site)"],
		value_font=FONT_PLAIN,
		value_size=8.0,
	)
	sheet.money_box(
		right_x,
		top,
		right_w,
		30,
		"1  Nonemployee compensation",
		form_data.get("box1_nonemployee_compensation"),
	)
	sheet.box(
		right_x,
		top + 30,
		right_w,
		36,
		"2  Payer made direct sales totalling $5,000 or more of consumer products to recipient for resale",
		"",
	)
	sheet.checkbox(right_x + right_w - 18, top + 44, "", bool(form_data.get("box2_direct_sales_indicator")))

	sheet.box(MARGIN, top + 66, left_w / 2, 28, "PAYER'S TIN", payer["ein"])
	sheet.box(MARGIN + left_w / 2, top + 66, left_w / 2, 28, "RECIPIENT'S TIN", tin)
	sheet.box(right_x, top + 66, right_w, 28, "3", "")

	sheet.box(MARGIN, top + 94, left_w, 26, "RECIPIENT'S name", name)
	sheet.money_box(
		right_x,
		top + 94,
		right_w,
		26,
		"4  Federal income tax withheld",
		form_data.get("box4_federal_income_tax_withheld"),
	)

	sheet.box(
		MARGIN,
		top + 120,
		left_w,
		48,
		"Street address, city or town, state, ZIP code",
		address or ["(not recorded on this site)"],
		value_font=FONT_PLAIN,
		value_size=8.0,
	)
	sheet.box(
		right_x,
		top + 120,
		right_w,
		24,
		"Account number (see instructions)",
		_clean(block.get("party") or info.get("party") or ""),
		value_size=7.5,
	)
	sheet.box(
		right_x,
		top + 144,
		right_w,
		24,
		"Reportable at the $" + _money(form_data.get("reporting_threshold")) + " threshold",
		"YES" if form_data.get("reportable") else "NO",
		value_align="right",
	)

	sheet.top = top + 168 + 6
	_nec_state_table(sheet, form_data)

	extra = []
	if not form_data.get("reportable"):
		extra.append(
			f"This recipient is UNDER the ${_money(form_data.get('reporting_threshold'))} "
			"reporting threshold and had no backup withholding, so no 1099-NEC is required. "
			"The figures are computed and printed anyway, because an employer deciding not "
			"to file still wants to see what the total was."
		)
	extra.append(
		f"Box 1 totals {form_data.get('payment_count') or 0} payment(s) posted to this "
		"recipient in the year. The taxpayer identification number is printed as four "
		"digits because this system stores four and never nine — complete the rest from "
		"the signed W-9 before anything is filed or furnished."
	)
	_notes(sheet, form_data, extra)
	return sheet.render()


def _nec_state_table(sheet: _Sheet, form_data: dict) -> None:
	"""Boxes 5, 6 and 7, one row per state."""
	columns = (
		("5  State tax withheld", 150.0, "box5_state_tax_withheld", "money"),
		("6  State/Payer's state no.", 240.0, "box6_payer_state_number", "text"),
		("7  State income", 150.0, "box7_state_income", "money"),
	)
	rows = list(form_data.get("state_boxes") or []) or [{}]
	sheet.room_for(20 + 20 * len(rows))

	top = sheet.top
	x = MARGIN
	for label, width, _key, _kind in columns:
		sheet.rect(x, top, width, 20)
		sheet.text(x + 3, top + SIZE_LABEL + 2.5, label, FONT_LABEL, SIZE_LABEL)
		x += width
	for row_index, row in enumerate(rows):
		row_top = top + 20 + row_index * 20
		x = MARGIN
		for _label, width, key, kind in columns:
			if kind == "money":
				value = _money(row.get(key))
			else:
				state = _clean(row.get("box6_state") or "")
				number = _clean(row.get(key) or "")
				value = f"{state}  {number}".strip()
			sheet.box(
				x,
				row_top,
				width,
				20,
				"",
				value,
				value_size=8.0,
				value_align="right" if kind == "money" else "left",
			)
			x += width
	sheet.top = top + 20 + 20 * len(rows)


# ── Form 941 ────────────────────────────────────────────────────────────────

#: Part 1 of Form 941, in the order and wording of the real return. Each entry
#: is (line label, key in form_data, kind). `kind` decides how it draws: a
#: money line, a count, a two-part line with its own wage column, or a rule.
_941_LINES = (
	(
		"1",
		"Number of employees who received wages, tips, or other compensation",
		"line1_number_of_employees",
		"count",
	),
	("2", "Wages, tips, and other compensation", "line2_wages_tips_other_compensation", "money"),
	(
		"3",
		"Federal income tax withheld from wages, tips, and other compensation",
		"line3_federal_income_tax_withheld",
		"money",
	),
	(
		"4",
		"If no wages, tips, and other compensation are subject to social security "
		"or Medicare tax, check and go to line 6",
		"line4_no_wages_subject_to_ss_medicare",
		"check",
	),
	("5a", "Taxable social security wages", ("line5a_taxable_social_security_wages", "line5a_tax"), "pair"),
	("5b", "Taxable social security tips", ("line5b_taxable_social_security_tips", "line5b_tax"), "pair"),
	("5c", "Taxable Medicare wages and tips", ("line5c_taxable_medicare_wages", "line5c_tax"), "pair"),
	(
		"5d",
		"Taxable wages and tips subject to Additional Medicare Tax withholding",
		("line5d_wages_subject_to_additional_medicare", "line5d_tax"),
		"pair",
	),
	(
		"5e",
		"Total social security and Medicare taxes. Add lines 5a to 5d",
		"line5e_total_social_security_and_medicare",
		"money",
	),
	(
		"5f",
		"Section 3121(q) Notice and Demand - tax due on unreported tips",
		"line5f_section_3121q_notice_and_demand",
		"money",
	),
	(
		"6",
		"Total taxes before adjustments. Add lines 3, 5e, and 5f",
		"line6_total_taxes_before_adjustments",
		"money",
	),
	(
		"7",
		"Current quarter's adjustment for fractions of cents",
		"line7_fractions_of_cents_adjustment",
		"money",
	),
	("8", "Current quarter's adjustment for sick pay", "line8_sick_pay_adjustment", "money"),
	(
		"9",
		"Current quarter's adjustments for tips and group-term life insurance",
		"line9_tips_and_group_term_life_adjustment",
		"money",
	),
	(
		"10",
		"Total taxes after adjustments. Combine lines 6 through 9",
		"line10_total_taxes_after_adjustments",
		"money",
	),
	(
		"11",
		"Qualified small business payroll tax credit for increasing research activities",
		"line11_small_business_payroll_tax_credit",
		"money",
	),
	(
		"12",
		"Total taxes after adjustments and nonrefundable credits. Subtract line 11 from line 10",
		"line12_total_taxes_after_credits",
		"money",
	),
	("13", "Total deposits for this quarter", "line13_total_deposits", "money"),
	(
		"14",
		"Balance due. If line 12 is more than line 13, enter the difference",
		"line14_balance_due",
		"money",
	),
	(
		"15",
		"Overpayment. If line 13 is more than line 12, enter the difference",
		"line15_overpayment",
		"money",
	),
)

_QUARTER_LABELS = (
	("Q1", "1: January, February, March"),
	("Q2", "2: April, May, June"),
	("Q3", "3: July, August, September"),
	("Q4", "4: October, November, December"),
)


def render_941_pdf(form_data: dict, company_info: dict) -> bytes:
	"""Render Form 941 Employer's Quarterly Federal Tax Return PDF.

	Args:
		form_data: What `form_generators.generate_941_data` returned.
		company_info: The employer block, consulted only where `form_data` is
			silent — `name`, `ein`, `address`.

	Returns:
		PDF bytes. Part 1, lines 1 through 15, in the return's own numbering.
	"""
	form_data = dict(form_data or {})
	year = form_data.get("tax_year") or ""
	quarter = str(form_data.get("quarter") or "")
	sheet = _sheet_for("941", form_data, f"Employer's Quarterly Federal Tax Return {quarter} {year}")
	employer = _employer(form_data, company_info)

	sheet.masthead(
		"Form 941",
		"Employer's QUARTERLY Federal Tax Return",
		f"{quarter} {year}".strip(),
	)

	top = sheet.top
	sheet.box(MARGIN, top, 170.0, 26, "Employer identification number (EIN)", employer["ein"])
	sheet.box(MARGIN + 170.0, top, CONTENT_WIDTH - 170.0, 26, "Name (not your trade name)", employer["name"])
	sheet.box(
		MARGIN,
		top + 26,
		CONTENT_WIDTH,
		42,
		"Address",
		employer["address"] or ["(no address recorded on this site)"],
		value_font=FONT_PLAIN,
		value_size=8.0,
	)

	sheet.box(MARGIN, top + 68, CONTENT_WIDTH, 30, f"Report for this quarter of {year}", "")
	tick_x = MARGIN + 6
	for code, label in _QUARTER_LABELS:
		tick_x += sheet.checkbox(tick_x, top + 84, label, code == quarter) + 12

	due = _first(form_data.get("due_date"))
	sheet.box(
		MARGIN,
		top + 98,
		CONTENT_WIDTH / 2,
		22,
		"Period covered",
		_period_line(form_data).replace("Period covered: ", ""),
		value_size=8.0,
	)
	sheet.box(
		MARGIN + CONTENT_WIDTH / 2,
		top + 98,
		CONTENT_WIDTH / 2,
		22,
		"Return due date",
		due or "(not computed)",
		value_size=8.0,
	)

	sheet.top = top + 120 + 4
	sheet.heading("Part 1: Answer these questions for this quarter")
	_941_line_table(sheet, form_data)

	extra = [
		"Line 1 counts the distinct employees paid anywhere in the quarter. The real "
		"return asks for those paid in the pay period including the 12th of the "
		"quarter's last month — a payroll register cannot see that directly, and for a "
		"steady crew the two are the same number.",
		"Line 13 is whatever deposit total was supplied. Deposits are made through "
		"EFTPS and this system does not see them, so a zero on line 13 means nobody "
		"told it, not that nothing was deposited.",
	]
	_notes(sheet, form_data, extra)
	return sheet.render()


def _941_line_table(sheet: _Sheet, form_data: dict) -> None:
	"""One row per line of Part 1, wage column on the left of the tax column."""
	label_w = 330.0
	wage_w = 105.0
	tax_w = CONTENT_WIDTH - label_w - wage_w
	wage_x = MARGIN + label_w
	tax_x = wage_x + wage_w

	sheet.room_for(16)
	head_top = sheet.top
	sheet.fill_rect(MARGIN, head_top, CONTENT_WIDTH, 14)
	sheet.rect(MARGIN, head_top, CONTENT_WIDTH, 14)
	sheet.text(MARGIN + 4, head_top + 10, "Line", FONT_LABEL_BOLD, SIZE_LABEL)
	sheet.text(
		wage_x + wage_w - 4,
		head_top + 10,
		"Column 1 - taxable wages",
		FONT_LABEL_BOLD,
		SIZE_LABEL,
		align="right",
	)
	sheet.text(tax_x + tax_w - 4, head_top + 10, "Column 2 - tax", FONT_LABEL_BOLD, SIZE_LABEL, align="right")
	sheet.top = head_top + 14

	for number, label, key, kind in _941_LINES:
		wrapped = sheet.wrap(label, label_w - 34, FONT_LABEL, SIZE_SMALL)
		height = max(16.0, 4.0 + len(wrapped) * (SIZE_SMALL + 2.0))
		sheet.room_for(height)
		row_top = sheet.top

		sheet.rect(MARGIN, row_top, label_w, height)
		sheet.text(MARGIN + 4, row_top + SIZE_SMALL + 3, number, FONT_LABEL_BOLD, SIZE_SMALL)
		for index, line in enumerate(wrapped):
			sheet.text(
				MARGIN + 26,
				row_top + SIZE_SMALL + 3 + index * (SIZE_SMALL + 2.0),
				line,
				FONT_LABEL,
				SIZE_SMALL,
			)

		if kind == "pair":
			wage_key, tax_key = key
			sheet.box(
				wage_x,
				row_top,
				wage_w,
				height,
				"",
				_money(form_data.get(wage_key)),
				value_size=8.5,
				value_align="right",
			)
			sheet.box(
				tax_x,
				row_top,
				tax_w,
				height,
				"",
				_money(form_data.get(tax_key)),
				value_size=8.5,
				value_align="right",
			)
		elif kind == "count":
			sheet.rect(wage_x, row_top, wage_w, height)
			sheet.box(
				tax_x,
				row_top,
				tax_w,
				height,
				"",
				_whole(form_data.get(key)),
				value_size=8.5,
				value_align="right",
			)
		elif kind == "check":
			sheet.rect(wage_x, row_top, wage_w, height)
			sheet.rect(tax_x, row_top, tax_w, height)
			sheet.checkbox(tax_x + tax_w - 22, row_top + (height - 7.5) / 2, "", bool(form_data.get(key)))
		else:
			sheet.rect(wage_x, row_top, wage_w, height)
			sheet.box(
				tax_x,
				row_top,
				tax_w,
				height,
				"",
				_money(form_data.get(key)),
				value_size=8.5,
				value_align="right",
			)
		sheet.top = row_top + height


# ── Oregon Form OR-WR ───────────────────────────────────────────────────────

#: The columns of OR-WR's quarterly grid, and where each comes from.
_OR_WR_COLUMNS = (
	("Oregon wages", "or_wages"),
	("Income tax withheld", "or_income_tax"),
	("Statewide transit tax", "or_transit_tax"),
	("Paid Leave - employee", "or_paid_leave_employee"),
	("Paid Leave - employer", "or_paid_leave_employer"),
)

_OR_WR_QUARTER_LABELS = (
	("Q1", "1st quarter"),
	("Q2", "2nd quarter"),
	("Q3", "3rd quarter"),
	("Q4", "4th quarter"),
)

#: What OR-WR actually reconciles: the annual total against the four filed OQs.
_OR_WR_RECONCILED = (
	("or_income_tax", "Oregon income tax withheld"),
	("or_transit_tax", "Statewide transit tax"),
	("or_paid_leave_employee", "Paid Leave Oregon - employee share"),
)


def render_or_wr_pdf(form_data: dict, company_info: dict) -> bytes:
	"""Render Oregon Form OR-WR Annual Withholding Reconciliation PDF.

	Args:
		form_data: What `form_generators.generate_or_wr_data` returned.
		company_info: The employer block, consulted only where `form_data` is
			silent.

	Returns:
		PDF bytes. The quarterly grid, the annual totals, and the reconciliation
		against what was filed on the four OQ reports — which is the whole point
		of the form.
	"""
	form_data = dict(form_data or {})
	year = form_data.get("tax_year") or ""
	sheet = _sheet_for("OR-WR", form_data, f"Oregon annual withholding reconciliation {year}")
	employer = _employer(form_data, company_info)

	sheet.masthead(
		"Form OR-WR",
		"Oregon Annual Withholding Tax Reconciliation Report",
		str(year),
	)

	top = sheet.top
	sheet.box(
		MARGIN,
		top,
		160.0,
		26,
		"Oregon BIN",
		_first(form_data.get("oregon_bin")) or "(not recorded on this site)",
	)
	sheet.box(MARGIN + 160.0, top, 160.0, 26, "Federal employer identification number", employer["ein"])
	sheet.box(
		MARGIN + 320.0,
		top,
		CONTENT_WIDTH - 320.0,
		26,
		"Return due date",
		_first(form_data.get("due_date")),
		value_size=8.0,
	)
	sheet.box(MARGIN, top + 26, CONTENT_WIDTH, 26, "Business name", employer["name"])
	sheet.top = top + 52 + 4

	sheet.heading(f"Quarterly detail for {year}")
	_or_wr_quarter_table(sheet, form_data)

	sheet.heading("Reconciliation: the year against the four OQ reports as filed")
	_or_wr_reconciliation(sheet, form_data)

	reconciles = form_data.get("reconciles")
	extra = []
	if reconciles is None:
		extra.append(
			"Nothing was supplied for what the four OQ reports actually carried, so this "
			"page is the computed annual total with nothing to reconcile against. OR-WR's "
			"whole purpose is the comparison; supply the filed figures to get an answer "
			"rather than a total."
		)
	elif reconciles is False:
		extra.append(
			"THE ANNUAL TOTALS DO NOT MATCH THE OQ FIGURES SUPPLIED. The reconciliation "
			"table above names which line differs and by how much. An OR-WR filed on an "
			"unexplained difference is an assessment letter."
		)
	else:
		extra.append("The computed annual totals agree with the four OQ reports as filed, to the cent.")
	_notes(sheet, form_data, extra)
	return sheet.render()


def _or_wr_quarter_table(sheet: _Sheet, form_data: dict) -> None:
	by_quarter = dict(form_data.get("by_quarter") or {})
	annual = dict(form_data.get("annual") or {})
	quarters_sum = dict(form_data.get("quarters_sum") or {})

	label_w = 100.0
	column_w = (CONTENT_WIDTH - label_w) / len(_OR_WR_COLUMNS)
	sheet.room_for(28 + 18 * (len(_OR_WR_QUARTER_LABELS) + 2))

	head_top = sheet.top
	sheet.fill_rect(MARGIN, head_top, CONTENT_WIDTH, 26)
	sheet.rect(MARGIN, head_top, label_w, 26)
	sheet.text(MARGIN + 4, head_top + 16, "Quarter", FONT_LABEL_BOLD, SIZE_LABEL)
	for index, (label, _key) in enumerate(_OR_WR_COLUMNS):
		x = MARGIN + label_w + index * column_w
		sheet.rect(x, head_top, column_w, 26)
		for line_index, line in enumerate(sheet.wrap(label, column_w - 6, FONT_LABEL_BOLD, SIZE_LABEL)[:3]):
			sheet.text(
				x + 3, head_top + SIZE_LABEL + 2.5 + line_index * 7.5, line, FONT_LABEL_BOLD, SIZE_LABEL
			)
	sheet.top = head_top + 26

	def data_row(label: str, values: dict, bold: bool = False) -> None:
		row_top = sheet.top
		sheet.rect(MARGIN, row_top, label_w, 18)
		sheet.text(MARGIN + 4, row_top + 12.5, label, FONT_LABEL_BOLD if bold else FONT_LABEL, SIZE_SMALL)
		for index, (_label, key) in enumerate(_OR_WR_COLUMNS):
			x = MARGIN + label_w + index * column_w
			sheet.box(
				x, row_top, column_w, 18, "", _money(values.get(key)), value_size=8.0, value_align="right"
			)
		sheet.top = row_top + 18

	for code, label in _OR_WR_QUARTER_LABELS:
		data_row(label, dict(by_quarter.get(code) or {}))
	data_row("Sum of quarters", quarters_sum, bold=True)
	data_row("Annual total", annual, bold=True)


def _or_wr_reconciliation(sheet: _Sheet, form_data: dict) -> None:
	table = dict(form_data.get("reconciliation") or {})
	label_w = 240.0
	column_w = (CONTENT_WIDTH - label_w) / 3
	sheet.room_for(20 + 18 * (len(_OR_WR_RECONCILED) + 1))

	head_top = sheet.top
	sheet.fill_rect(MARGIN, head_top, CONTENT_WIDTH, 16)
	sheet.rect(MARGIN, head_top, label_w, 16)
	sheet.text(MARGIN + 4, head_top + 11, "Line", FONT_LABEL_BOLD, SIZE_LABEL)
	for index, heading in enumerate(("Annual total", "Filed on the OQs", "Difference")):
		x = MARGIN + label_w + index * column_w
		sheet.rect(x, head_top, column_w, 16)
		sheet.text(x + column_w - 4, head_top + 11, heading, FONT_LABEL_BOLD, SIZE_LABEL, align="right")
	sheet.top = head_top + 16

	for key, label in _OR_WR_RECONCILED:
		row = dict(table.get(key) or {})
		row_top = sheet.top
		sheet.rect(MARGIN, row_top, label_w, 18)
		sheet.text(MARGIN + 4, row_top + 12.5, label, FONT_LABEL, SIZE_SMALL)
		for index, value_key in enumerate(("annual_total", "quarterly_filed", "difference")):
			x = MARGIN + label_w + index * column_w
			sheet.box(
				x, row_top, column_w, 18, "", _money(row.get(value_key)), value_size=8.0, value_align="right"
			)
		sheet.top = row_top + 18

	reconciles = form_data.get("reconciles")
	verdict = {
		True: "RECONCILES - the year agrees with the four OQ reports.",
		False: "DOES NOT RECONCILE - see the difference column.",
	}.get(reconciles, "NOT RECONCILED - no filed OQ figures were supplied.")
	sheet.spacer(4)
	sheet.paragraph(verdict, size=8.0, font=FONT_LABEL_BOLD)


# ── Oregon Form OQ ──────────────────────────────────────────────────────────

#: OQ's four programs, in the order the combined return puts them.
_OQ_PROGRAMS = (
	("Subject wages (Oregon)", "subject_wages"),
	("State income tax withheld", "state_withholding"),
	("Statewide transit tax subject wages", "transit_tax_subject_wages"),
	("Statewide transit tax withheld", "statewide_transit_tax"),
	("UI subject wages", "ui_subject_wages"),
	("UI tax", "ui_tax"),
	("Paid Leave Oregon - employee share", "paid_leave_employee"),
	("Paid Leave Oregon - employer share", "paid_leave_employer"),
	("Paid Leave Oregon - total", "paid_leave_total"),
	("Workers' compensation assessment", "workers_comp"),
)


def render_or_oq_pdf(form_data: dict, company_info: dict) -> bytes:
	"""Render Oregon Form OQ Quarterly Tax Report PDF.

	Args:
		form_data: What `form_generators.generate_or_oq_data` returned.
		company_info: The employer block, consulted only where `form_data` is
			silent.

	Returns:
		PDF bytes. The four programs one combined return covers, the per-month
		employee counts the form asks for by name, and the total due.
	"""
	form_data = dict(form_data or {})
	year = form_data.get("tax_year") or ""
	quarter = str(form_data.get("quarter") or "")
	sheet = _sheet_for("OQ", form_data, f"Oregon quarterly tax report {quarter} {year}")
	employer = _employer(form_data, company_info)

	sheet.masthead(
		"Form OQ",
		"Oregon Quarterly Tax Report (combined payroll)",
		f"{quarter} {year}".strip(),
	)

	top = sheet.top
	sheet.box(
		MARGIN,
		top,
		160.0,
		26,
		"Oregon BIN",
		_first(form_data.get("oregon_bin")) or "(not recorded on this site)",
	)
	sheet.box(MARGIN + 160.0, top, 160.0, 26, "Federal employer identification number", employer["ein"])
	sheet.box(
		MARGIN + 320.0,
		top,
		CONTENT_WIDTH - 320.0,
		26,
		"Return due date",
		_first(form_data.get("due_date")),
		value_size=8.0,
	)
	sheet.box(MARGIN, top + 26, 330.0, 26, "Business name", employer["name"])
	sheet.box(
		MARGIN + 330.0,
		top + 26,
		CONTENT_WIDTH - 330.0,
		26,
		"Quarter covered",
		_period_line(form_data).replace("Period covered: ", ""),
		value_size=7.5,
	)
	sheet.top = top + 52 + 4

	sheet.heading("Monthly employee counts")
	_oq_month_boxes(sheet, form_data)

	sheet.heading("Subject wages and tax by program")
	_amount_table(sheet, _OQ_PROGRAMS, form_data)

	sheet.spacer(4)
	total_top = sheet.top
	sheet.room_for(24)
	sheet.box(
		MARGIN,
		total_top,
		330.0,
		22,
		"Unemployment insurance rate applied",
		f"{_money(form_data.get('ui_rate'))} %",
		value_align="right",
	)
	sheet.box(
		MARGIN + 330.0,
		total_top,
		CONTENT_WIDTH - 330.0,
		22,
		"TOTAL DUE",
		_money(form_data.get("total_due")),
		value_align="right",
		label_font=FONT_LABEL_BOLD,
	)
	sheet.top = total_top + 22

	extra = [
		f"{form_data.get('employee_count') or 0} employee(s) and "
		f"{_money(form_data.get('total_hours'))} hour(s) of Oregon work in the quarter, "
		f"from {form_data.get('slip_count') or 0} payroll slip(s).",
		"The unemployment-insurance rate is assigned to each employer by the Oregon "
		"Employment Department every year and this system does not know it. A rate of "
		"0.00 means none was supplied, not that none applies.",
	]
	_notes(sheet, form_data, extra)
	return sheet.render()


def _oq_month_boxes(sheet: _Sheet, form_data: dict) -> None:
	"""The three per-month counts, side by side, as the form asks for them."""
	counts = dict(form_data.get("monthly_employee_counts") or {})
	months = list(counts.items()) or [("Month 1", 0), ("Month 2", 0), ("Month 3", 0)]
	sheet.room_for(30)
	top = sheet.top
	width = CONTENT_WIDTH / max(3, len(months))
	for index, (month, count) in enumerate(months):
		sheet.box(
			MARGIN + index * width,
			top,
			width,
			26,
			f"Employees paid in {month}",
			_whole(count),
			value_align="right",
		)
	sheet.top = top + 26


def _amount_table(sheet: _Sheet, rows, form_data: dict) -> None:
	"""A two-column label/amount table. Every state form ends up wanting one."""
	label_w = CONTENT_WIDTH - 130.0
	for label, key in rows:
		sheet.room_for(18)
		row_top = sheet.top
		sheet.rect(MARGIN, row_top, label_w, 18)
		sheet.text(MARGIN + 4, row_top + 12.5, label, FONT_LABEL, SIZE_SMALL)
		sheet.box(
			MARGIN + label_w,
			row_top,
			130.0,
			18,
			"",
			_money(form_data.get(key)),
			value_size=8.5,
			value_align="right",
		)
		sheet.top = row_top + 18


# ── Washington ESD quarterly report ─────────────────────────────────────────

#: The columns of the wage-and-hour detail ESD asks for, per employee.
_WA_COLUMNS = (
	("SSN", 92.0, "ssn_display", "text"),
	("Employee name", 168.0, "employee_name", "text"),
	("Hours worked", 66.0, "hours", "whole"),
	("Total wages", 74.0, "wages", "money"),
	("Taxable wages", 74.0, "taxable_wages", "money"),
	("Excess wages", 66.0, "excess_wages", "money"),
)

#: The tax summary under the detail: what is owed, by programme.
_WA_PROGRAMS = (
	("Total gross wages", "total_wages"),
	("Total taxable wages", "total_taxable_wages"),
	("Total excess wages", "total_excess_wages"),
	("Unemployment insurance tax", "ui_tax"),
	("Paid Family & Medical Leave - employee premium", "pfml_employee_premium"),
	("Paid Family & Medical Leave - employer premium", "pfml_employer_premium"),
	("Paid Family & Medical Leave - total premium", "pfml_total_premium"),
	("WA Cares Fund - employee premium", "wa_cares_employee_premium"),
	("Labor & Industries - employee share", "labor_and_industries_employee"),
	("Labor & Industries - employer share", "labor_and_industries_employer"),
)


def render_wa_esd_pdf(form_data: dict, company_info: dict) -> bytes:
	"""Render Washington ESD Quarterly Report PDF.

	Args:
		form_data: What `form_generators.generate_wa_esd_data` returned.
		company_info: The employer block, consulted only where `form_data` is
			silent.

	Returns:
		PDF bytes. The per-employee wage-and-hour detail — which is the part ESD
		will reject the report without — then the tax summary. The detail table
		paginates; every page carries the header row again.
	"""
	form_data = dict(form_data or {})
	year = form_data.get("tax_year") or ""
	quarter = str(form_data.get("quarter") or "")
	sheet = _sheet_for("WA-ESD", form_data, f"Washington ESD quarterly report {quarter} {year}")
	employer = _employer(form_data, company_info)

	sheet.masthead(
		"WA ESD Quarterly Report",
		"Employment Security Department - quarterly wage detail and tax report",
		f"{quarter} {year}".strip(),
	)

	top = sheet.top
	sheet.box(
		MARGIN,
		top,
		170.0,
		26,
		"ESD account number",
		_first(form_data.get("esd_account_number")) or "(not recorded on this site)",
	)
	sheet.box(MARGIN + 170.0, top, 170.0, 26, "Federal employer identification number", employer["ein"])
	sheet.box(
		MARGIN + 340.0,
		top,
		CONTENT_WIDTH - 340.0,
		26,
		"Return due date",
		_first(form_data.get("due_date")),
		value_size=8.0,
	)
	sheet.box(MARGIN, top + 26, 330.0, 26, "Business name", employer["name"])
	sheet.box(
		MARGIN + 330.0,
		top + 26,
		CONTENT_WIDTH - 330.0,
		26,
		"Quarter covered",
		_period_line(form_data).replace("Period covered: ", ""),
		value_size=7.5,
	)
	sheet.top = top + 52 + 4

	sheet.heading("Wage and hour detail - one row per employee")
	_wa_employee_table(sheet, form_data)

	sheet.heading("Tax summary")
	_amount_table(sheet, _WA_PROGRAMS, form_data)

	sheet.spacer(4)
	sheet.room_for(24)
	total_top = sheet.top
	sheet.box(
		MARGIN,
		total_top,
		330.0,
		22,
		"Unemployment insurance rate applied",
		f"{_money(form_data.get('ui_rate'))} %",
		value_align="right",
	)
	sheet.box(
		MARGIN + 330.0,
		total_top,
		CONTENT_WIDTH - 330.0,
		22,
		"TOTAL DUE",
		_money(form_data.get("total_due")),
		value_align="right",
		label_font=FONT_LABEL_BOLD,
	)
	sheet.top = total_top + 22

	extra = [
		"Hours are not incidental on this report. Washington's benefit eligibility is an "
		"hours test, so ESD requires hours worked per employee and will reject a report "
		"filed with wages and no hours.",
		"Each Social Security number is printed as four digits because this system stores "
		"four and never nine. The report cannot be filed until each one is completed by "
		"hand from the employee's I-9.",
	]
	_notes(sheet, form_data, extra)
	return sheet.render()


def _wa_employee_table(sheet: _Sheet, form_data: dict) -> None:
	"""The per-employee detail, repeating its header row on every page.

	A row is never split across a page break: half a wage figure at the foot of
	a page is how a number gets lost without anybody noticing.
	"""
	rows = list(form_data.get("employees") or [])

	def header() -> None:
		sheet.room_for(16 + 16)
		head_top = sheet.top
		sheet.fill_rect(MARGIN, head_top, CONTENT_WIDTH, 16)
		x = MARGIN
		for label, width, _key, kind in _WA_COLUMNS:
			sheet.rect(x, head_top, width, 16)
			if kind == "text":
				sheet.text(x + 4, head_top + 11, label, FONT_LABEL_BOLD, SIZE_LABEL)
			else:
				sheet.text(x + width - 4, head_top + 11, label, FONT_LABEL_BOLD, SIZE_LABEL, align="right")
			x += width
		sheet.top = head_top + 16

	header()
	if not rows:
		sheet.room_for(16)
		row_top = sheet.top
		sheet.rect(MARGIN, row_top, CONTENT_WIDTH, 16)
		sheet.text(MARGIN + 4, row_top + 11.5, "No Washington wages in this quarter.", FONT_LABEL, SIZE_SMALL)
		sheet.top = row_top + 16
		return

	for row in rows:
		if sheet.top + 16 > FOOTER_LIMIT:
			sheet.page_break()
			header()
		row_top = sheet.top
		x = MARGIN
		for _label, width, key, kind in _WA_COLUMNS:
			if kind == "money":
				value, align = _money(row.get(key)), "right"
			elif kind == "whole":
				value, align = _whole(row.get(key)), "right"
			elif key == "ssn_display":
				value, align = _bare_ssn(row.get(key)) or "XXX-XX-____", "left"
			else:
				value, align = _clean(row.get(key) or ""), "left"
			sheet.box(x, row_top, width, 16, "", value, value_size=7.5, value_align=align)
			x += width
		sheet.top = row_top + 16

	# The totals row, kept with at least one data row above it.
	if sheet.top + 16 > FOOTER_LIMIT:
		sheet.page_break()
		header()
	row_top = sheet.top
	totals = {
		"employee_name": f"TOTAL - {len(rows)} employee(s)",
		"hours": form_data.get("total_hours"),
		"wages": form_data.get("total_wages"),
		"taxable_wages": form_data.get("total_taxable_wages"),
		"excess_wages": form_data.get("total_excess_wages"),
	}
	sheet.fill_rect(MARGIN, row_top, CONTENT_WIDTH, 16, grey=0.93)
	x = MARGIN
	for _label, width, key, kind in _WA_COLUMNS:
		if kind == "money":
			value, align = _money(totals.get(key)), "right"
		elif kind == "whole":
			value, align = _whole(totals.get(key)), "right"
		else:
			value, align = _clean(totals.get(key) or ""), "left"
		sheet.box(x, row_top, width, 16, "", value, value_size=7.5, value_align=align, value_font=FONT_VALUE)
		x += width
	sheet.top = row_top + 16


# ── Form 940 and W-3 ── v0.259.0 ────────────────────────────────────────────

_940_LINES = (
	("Line 3 - Total payments to all employees", "line3_total_payments"),
	("Line 4 - Payments exempt from FUTA tax", "line4_payments_exempt_from_futa"),
	("Line 5 - Payments over the $7,000 wage base", "line5_payments_over_wage_base"),
	("Line 6 - Subtotal (line 4 + line 5)", "line6_subtotal"),
	("Line 7 - Total taxable FUTA wages", "line7_total_taxable_futa_wages"),
	("Line 8 - FUTA tax before adjustments", "line8_futa_tax_before_adjustments"),
	("Line 11 - Credit reduction", "line11_credit_reduction"),
	("Line 12 - Total FUTA tax after adjustments", "line12_total_futa_tax"),
	("Line 13 - FUTA tax deposited for the year", "line13_futa_tax_deposited"),
	("Line 14 - Balance due", "line14_balance_due"),
	("Line 15 - Overpayment", "line15_overpayment"),
	("Line 17 - Total tax liability for the year", "line17_total_liability"),
)

_W3_BOXES = (
	("1 - Wages, tips, other compensation", "box1_wages"),
	("2 - Federal income tax withheld", "box2_federal_income_tax_withheld"),
	("3 - Social security wages", "box3_social_security_wages"),
	("4 - Social security tax withheld", "box4_social_security_tax_withheld"),
	("5 - Medicare wages and tips", "box5_medicare_wages"),
	("6 - Medicare tax withheld", "box6_medicare_tax_withheld"),
	("7 - Social security tips", "box7_social_security_tips"),
	("8 - Allocated tips", "box8_allocated_tips"),
	("14 - Income tax withheld by third-party payer", "box14_income_tax_withheld_by_third_party_payer"),
)


def render_940_pdf(form_data: dict, company_info: dict) -> bytes:
	"""Form 940 working copy: Part 2 and 3 lines, the quarterly liabilities, and the notes."""
	form_data = dict(form_data or {})
	year = form_data.get("tax_year") or ""
	sheet = _sheet_for("940", form_data, f"Employer's Annual Federal Unemployment (FUTA) Tax Return {year}")
	employer = _employer(form_data, company_info)
	sheet.masthead("Form 940", "Employer's Annual Federal Unemployment (FUTA) Tax Return", str(year))
	top = sheet.top
	sheet.box(MARGIN, top, 170.0, 26, "Employer identification number (EIN)", employer["ein"])
	sheet.box(MARGIN + 170.0, top, CONTENT_WIDTH - 170.0, 26, "Name (not your trade name)", employer["name"])
	sheet.box(MARGIN, top + 26, CONTENT_WIDTH, 42, "Address",
	          employer["address"] or ["(no address recorded on this site)"], value_font=FONT_PLAIN, value_size=8.0)
	sheet.top = top + 68 + 4
	sheet.heading("Parts 2 and 3: FUTA tax")
	_amount_table(sheet, _940_LINES, form_data)
	quarters = form_data.get("line16_quarterly_liabilities") or {}
	if quarters:
		sheet.heading("Part 5, line 16: FUTA liability by quarter")
		_amount_table(sheet, [(f"16 - {q}", q) for q in sorted(quarters)], quarters)
	extra = [
		"Line 13 is whatever deposit total was supplied. FUTA deposits go through EFTPS and this system does not "
		"see them, so a zero on line 13 means nobody told it, not that nothing was deposited.",
		"Agricultural employers: FUTA covers farm labour only if cash wages reached $20,000 in some quarter or 10 "
		"or more farmworkers were employed in 20 or more weeks. Read `agricultural_coverage` in the record first.",
	]
	_notes(sheet, form_data, extra)
	return sheet.render()


def render_w3_pdf(form_data: dict, company_info: dict) -> bytes:
	"""W-3 working copy: boxes b, c, e, f and 1-8, 14, and the state totals."""
	form_data = dict(form_data or {})
	year = form_data.get("tax_year") or ""
	sheet = _sheet_for("W-3", form_data, f"Transmittal of Wage and Tax Statements {year}")
	employer = _employer(form_data, company_info)
	sheet.masthead("Form W-3", "Transmittal of Wage and Tax Statements", str(year))
	top = sheet.top
	sheet.box(MARGIN, top, CONTENT_WIDTH / 2, 26, "b - Kind of payer", str(form_data.get("box_b_kind_of_payer") or ""))
	sheet.box(MARGIN + CONTENT_WIDTH / 2, top, CONTENT_WIDTH / 2, 26, "b - Kind of employer",
	          str(form_data.get("box_b_kind_of_employer") or ""))
	sheet.box(MARGIN, top + 26, 170.0, 26, "c - Total number of Forms W-2",
	          str(form_data.get("box_c_total_w2_forms") or 0))
	sheet.box(MARGIN + 170.0, top + 26, CONTENT_WIDTH - 170.0, 26, "e - Employer identification number (EIN)",
	          employer["ein"])
	sheet.box(MARGIN, top + 52, CONTENT_WIDTH, 42, "f - Employer's name and address",
	          [employer["name"], *(employer["address"] or [])], value_font=FONT_PLAIN, value_size=8.0)
	sheet.top = top + 94 + 4
	sheet.heading("Totals of the Forms W-2")
	_amount_table(sheet, _W3_BOXES, form_data)
	states = form_data.get("state_boxes") or []
	if states:
		sheet.heading("Boxes 15-17: by state")
		for state in states:
			label = f"{state.get('box15_state')} ({state.get('box15_employer_state_id') or 'no state ID'})"
			_amount_table(sheet, [(f"16 - {label} state wages", "box16_state_wages"),
			                      (f"17 - {label} state income tax", "box17_state_income_tax")], state)
	_notes(sheet, form_data, [])
	return sheet.render()


# ── Dispatch ────────────────────────────────────────────────────────────────

#: Which renderer draws which form, and whether it needs a recipient block.
#: Same shape and the same reason as `form_generators.generate_form_data`: the
#: "which arguments does this form take" question belongs in one place rather
#: than repeated in every caller.
RENDERERS = {
	"W-2": render_w2_pdf,
	"1099-NEC": render_1099_nec_pdf,
	"941": render_941_pdf,
	"OR-WR": render_or_wr_pdf,
	"OQ": render_or_oq_pdf,
	"WA-ESD": render_wa_esd_pdf,
	"940": render_940_pdf,
	"W-3": render_w3_pdf,
}

#: The two forms whose renderer takes a third argument: the person it is about.
PER_RECIPIENT = ("W-2", "1099-NEC")


def render_form_pdf(
	form_type: str,
	form_data: dict,
	company_info: dict | None = None,
	subject_info: dict | None = None,
) -> bytes:
	"""Route to the right renderer. The one entry point a tool needs."""
	require()
	renderer = RENDERERS.get(form_type)
	if renderer is None:
		raise ToolError(
			f"no PDF layout for form type {form_type!r}. Known forms: {', '.join(sorted(RENDERERS))}."
		)
	if form_type in PER_RECIPIENT:
		return renderer(form_data or {}, company_info or {}, subject_info or {})
	return renderer(form_data or {}, company_info or {})


def file_name_for(form_type: str, form_data: dict, subject: str = "") -> str:
	"""What the attached file is called. Sortable, and says what it is on sight."""
	parts = [str(form_type).replace("/", "-")]
	year = form_data.get("tax_year")
	if year:
		parts.append(str(year))
	quarter = form_data.get("quarter")
	if quarter:
		parts.append(str(quarter))
	if subject:
		parts.append("".join(c if c.isalnum() or c in "-_" else "-" for c in str(subject)).strip("-"))
	return "-".join(part for part in parts if part) + ".pdf"
